apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlos
  labels:
    app: htmlos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmlos
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: htmlos
    spec:
      containers:
      - name: htmlos
        image: krushnakant241/mywebos:v1
        ports:
        - containerPort: 80
          name: htmlos
        volumeMounts:
        - name: htmlos-persistent-storage
          mountPath: /var/www/html
      volumes: 
      - name: htmlos-persistent-storage
        persistentVolumeClaim:
          claimName: htmlos-pvc-claim
