apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpos-pvc-claim
  labels:
    name: phpospvcclaim
spec: 
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi
